// <auto-generated />
using System;
using DepartmentsApi.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentsApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentsApi.Models.Entities.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepartmentId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1L,
                            IsActive = true,
                            Name = "Main Department"
                        },
                        new
                        {
                            DepartmentId = 2L,
                            IsActive = true,
                            Name = "Department11",
                            ParentId = 1
                        },
                        new
                        {
                            DepartmentId = 3L,
                            IsActive = true,
                            Name = "Department12",
                            ParentId = 1
                        },
                        new
                        {
                            DepartmentId = 4L,
                            IsActive = true,
                            Name = "Department21",
                            ParentId = 2
                        },
                        new
                        {
                            DepartmentId = 5L,
                            IsActive = true,
                            Name = "Department22",
                            ParentId = 2
                        });
                });

            modelBuilder.Entity("DepartmentsApi.Models.Entities.Department", b =>
                {
                    b.HasOne("DepartmentsApi.Models.Entities.Department", "Parent")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
